### ISSUE TITLE
Dependency to ToFormal

### ISSUE THREAD

**Issue by chrissi007** [Eden-06/CROF#8]
There is a dependency to the ToFormal Package in CROM for the menu entry Generate CROM this is bad.

**Comment by Eden-06** [comment]
This dependency is due to the hard coupling of CROM and toformal, which should be resolved first.

**Comment by Eden-06** [comment]
Commit: [dcdbd72b4ebb1dcbd0ca0a13cd2d15c19530709a](https://github.com/Eden-06/CROF/commit/dcdbd72b4ebb1dcbd0ca0a13cd2d15c19530709a)  fixes this issue.
